name: auth_repository
description: Authenticaton repository
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  amplify_auth_cognito: ^0.2.10
  amplify_flutter: ^0.2.10
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0