name: amplify_auth
description: Simply Flutter exmaple using AWS Amplify Auth
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.0.2
  camera: ^0.9.4+5
  equatable: ^2.0.3
  flow_builder: 0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.1
#  google_fonts: ^2.2.0
  # path: ^1.8.0
  # path_provider: ^2.0.8

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
